apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appname }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appname }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appname }}
  template:
    metadata:
      labels:
        app: {{ .Values.appname }}
    spec:
      containers:
        - name: {{ .Values.appname }}
          image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.containerPort }}
          readinessProbe:
            httpGet:
              port: {{ .Values.containerPort }}
              path: /health
            initialDelaySeconds: 5
            failureThreshold: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              port: {{ .Values.containerPort }}
              path: /health
            initialDelaySeconds: 5
            periodSeconds: 300
          resources:
            requests:
              memory: 20Mi
              cpu: 5m
            limits:
              memory: 100Mi
              cpu: 100m
      imagePullSecrets:
        - name: pullsecret-{{ .Values.appname }}
