apiVersion: v1
kind: Secret
metadata:
  name: pullsecret-{{ .Values.appname }}
  namespace: {{ .Values.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.pullsecret}}
